### PR TITLE
added natsort option to ops.sort_bedframe

### PR DESCRIPTION
**Pull request by luisdiaz1997**
Added an extra option of natural sort passed as argument (natsort:bool, default to False) to sort_bedframe.

Reason:
It's nice to have your dataframe as chr1, chr2.... rather than chr1, chr10...

### CODE REVIEW

**Comment by gfudenberg** [comment]
thanks for the option! can you add some tests for the natsort in `test_ops.py`? 

also maybe we should make `natsorted=True` the default w/o viewframe-- thoughts @golobor @agalitsyna ?

**Comment by Phlya** [comment]
The issue is that natsorting is not a great default... We typically want chrX, chrY, chrM, but natsorting places M before X. And depending on the genome, it may be worse than that. So maybe we should allow to pass a custom sorting function, and natsort is then easy to use too?

**Comment by gfudenberg** [comment]
I think the idea was that custom sorting would be handled by passing a
view. The question is if natsorting is better or worse default than not.
I'd be ok with making some 'upgraded natsort' for the default that e.g.
sorts human, fly, and yeast chromosomes with the desired order.

**Comment by luisdiaz1997** [comment]
> The issue is that natsorting is not a perfect option... We typically want chrX, chrY, chrM, but natsorting places M before X. And depending on the genome, it may be worse than that. So maybe we should allow to pass a custom sorting function, and natsort is then easy to use too?

I implemented arrops.argnartsort in here since other functions like io.fileops.read_chromsizes use it by by default. I guess it would need a chrom_patterns=(r"^chr[0-9]+$", r"^chr[XY]$", r"^chrM$") argument as well to make it have X, Y, M.
image

That could be a solution, or make a new function that both read_chromsizes and sort_bedframe could use.

**Comment by gfudenberg** [comment]
Hi Luis, 
Discussed this again today-- going forward if the user wants chroms sorted in a different order, they should provide a view_df with the desired order. We won't be supporting natsort as the default, because of subtleties introduced by different organsisms. Instead, bioframe will have a set of common assemblies with sorts based on usage of the chromosome (e.g. for hg38 primary chromosomes, X, Y, then M, then unlocalized then unplaced 
https://github.com/open2c/bioframe/blob/92a20138e5ee9b323322e340bd661730889becff/bioframe/io/data/GRCh37.seqinfo.tsv

**Pull request closed without merging**
