### PR TITLE
Preserve coordinate dtypes

### PR DESCRIPTION
**Pull request by nvictus**
Changes `overlap` to preserve the underlying integer type of the coordinate columns <s>when casting output to nullable pandas dtypes.</s>

EDIT: Changed to least surprising behavior: 

1. Coordinate (`start` and `end`) columns in the input dataframes preserve dtypes in the output dataframe, when possible. 
2. Outer join operations that introduce null values into coordinate columns will exhibit the native casting behavior of the column dtype: i.e. numpy columns get cast to `float64` with NaNs while nullable pandas arrays remain unchanged (e.g. `UInt32` -> `UInt32`) and contain NAs.

If one is worried about input-dependent casting behavior, one can convert coord columns to nullable types before passing to `overlap` with the`.convert_dtypes()` method. `float64` output columns can also be forced into nullable `Int64` after overlap by applying `.convert_dtypes()` on the output.

### CODE REVIEW

**Comment by gfudenberg** [comment]
sounds nice! should we add something like the following to tests?
 
```python
df1.astype({"start": pd.Int64Dtype(), "end": pd.Int64Dtype()})
df2.astype({"start": uint32 "end": uint32})

overlap_dtypes = bioframe.overlap(df1, df2).dtypes
assert (df1.dtypes = overlap_dtypes[:3]).all()
assert (df2.dtypes = overlap_dtypes[3:]).all()

```

**Comment by nvictus** [comment]
Added tests.

**Review by gfudenberg — APPROVED** [review]
nice dtype test!

The only question I have is if the dtype conversions should go into a
```Notes ---- ``` section of the `overlap` docstring

**Comment by nvictus** [comment]
Added the note, and introduced an `ensure_nullable` option to force upcast to nullable dtypes in the input, which ensures the output coord columns are nullable (+ tests). Saves a few keystrokes from having to do it manually before applying `overlap`.

**Pull request merged**
